development:
  bucket: cfdg-test
  access_key_id: AKIAI4SMFTTLMHTNSY7A
  secret_access_key: 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
test:
  bucket: cfdg-test
  access_key_id: AKIAI4SMFTTLMHTNSY7A
  secret_access_key: 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
production:
  bucket: cfdg-test
  access_key_id: AKIAI4SMFTTLMHTNSY7A
  secret_access_key: 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